"""initial schema

Revision ID: 0f5e0bdac5c4
Revises: 
Create Date: 2026-06-27 15:02:47.825261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5e0bdac5c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('school_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('director_contact', sa.String(length=255), nullable=True, comment='t.me/username or @username of director'),
    sa.Column('admin_group_link', sa.String(length=512), nullable=True, comment='Invite link to admin Telegram group'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.Enum('teacher', 'student', 'parent', name='sectiontype'), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'teacher_lead', name='webuserrole'), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('telegram_contact', sa.String(length=255), nullable=True, comment='@username or t.me/link shown to students & parents'),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('extra_info', sa.Text(), nullable=True, comment="Free-form contact info e.g. 'Вайбер: +380...'"),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('target', sa.Enum('all', 'teachers', 'students', 'parents', 'class_students', 'class_parents', 'class_all', name='newstarget'), nullable=False),
    sa.Column('target_class_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['web_users.id'], ),
    sa.ForeignKeyConstraint(['target_class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_deliveries')
    op.drop_table('news')
    op.drop_table('web_users')
    op.drop_table('sections')
    op.drop_table('telegram_accounts')
    op.drop_table('school_config')
    op.drop_table('classes')
    # ### end Alembic commands ###
